/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as RoleRedirectRouteImport } from './routes/role-redirect'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as MerchantEmployeeRouteImport } from './routes/merchant-employee'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as AdminEmployeeRouteImport } from './routes/admin-employee'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OperationsIndexRouteImport } from './routes/operations.index'
import { Route as MerchantIndexRouteImport } from './routes/merchant.index'
import { Route as MerchantEmployeeIndexRouteImport } from './routes/merchant-employee.index'
import { Route as CustomerIndexRouteImport } from './routes/customer.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminEmployeeIndexRouteImport } from './routes/admin-employee.index'
import { Route as OperationsShipmentsRouteImport } from './routes/operations.shipments'
import { Route as OperationsReportsRouteImport } from './routes/operations.reports'
import { Route as OperationsOrdersRouteImport } from './routes/operations.orders'
import { Route as OperationsInventoryRouteImport } from './routes/operations.inventory'
import { Route as MerchantSubscriptionRouteImport } from './routes/merchant.subscription'
import { Route as MerchantSettlementsRouteImport } from './routes/merchant.settlements'
import { Route as MerchantSalesRouteImport } from './routes/merchant.sales'
import { Route as MerchantRegisterRouteImport } from './routes/merchant.register'
import { Route as MerchantProfileRouteImport } from './routes/merchant.profile'
import { Route as MerchantProductsRouteImport } from './routes/merchant.products'
import { Route as MerchantOrdersRouteImport } from './routes/merchant.orders'
import { Route as MerchantInventoryRouteImport } from './routes/merchant.inventory'
import { Route as MerchantEmployeesRouteImport } from './routes/merchant.employees'
import { Route as MerchantEmployeeReportsRouteImport } from './routes/merchant-employee.reports'
import { Route as MerchantEmployeeProductsRouteImport } from './routes/merchant-employee.products'
import { Route as MerchantEmployeeOrdersRouteImport } from './routes/merchant-employee.orders'
import { Route as MerchantEmployeeInventoryRouteImport } from './routes/merchant-employee.inventory'
import { Route as CustomerSupportRouteImport } from './routes/customer.support'
import { Route as CustomerSearchRouteImport } from './routes/customer.search'
import { Route as CustomerProfileRouteImport } from './routes/customer.profile'
import { Route as CustomerNotificationsRouteImport } from './routes/customer.notifications'
import { Route as CustomerCheckoutRouteImport } from './routes/customer.checkout'
import { Route as CustomerCategoriesRouteImport } from './routes/customer.categories'
import { Route as CustomerCartRouteImport } from './routes/customer.cart'
import { Route as CustomerAiSearchRouteImport } from './routes/customer.ai-search'
import { Route as CustomerAddressesRouteImport } from './routes/customer.addresses'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSupportTicketsRouteImport } from './routes/admin.support-tickets'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPackagesRouteImport } from './routes/admin.packages'
import { Route as AdminMerchantsRouteImport } from './routes/admin.merchants'
import { Route as AdminEmployeesRouteImport } from './routes/admin.employees'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as AdminEmployeeUsersRouteImport } from './routes/admin-employee.users'
import { Route as AdminEmployeeSupportTicketsRouteImport } from './routes/admin-employee.support-tickets'
import { Route as AdminEmployeeReportsRouteImport } from './routes/admin-employee.reports'
import { Route as AdminEmployeeProductsRouteImport } from './routes/admin-employee.products'
import { Route as AdminEmployeeMerchantsRouteImport } from './routes/admin-employee.merchants'
import { Route as AdminEmployeeApplicationsRouteImport } from './routes/admin-employee.applications'
import { Route as CustomerOrdersIndexRouteImport } from './routes/customer.orders.index'
import { Route as CustomerProductIdRouteImport } from './routes/customer.product.$id'
import { Route as CustomerOrdersIdRouteImport } from './routes/customer.orders.$id'
import { Route as CustomerCategoryIdRouteImport } from './routes/customer.category.$id'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleRedirectRoute = RoleRedirectRouteImport.update({
  id: '/role-redirect',
  path: '/role-redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantEmployeeRoute = MerchantEmployeeRouteImport.update({
  id: '/merchant-employee',
  path: '/merchant-employee',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmployeeRoute = AdminEmployeeRouteImport.update({
  id: '/admin-employee',
  path: '/admin-employee',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsIndexRoute = OperationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OperationsRoute,
} as any)
const MerchantIndexRoute = MerchantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantEmployeeIndexRoute = MerchantEmployeeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MerchantEmployeeRoute,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployeeIndexRoute = AdminEmployeeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminEmployeeRoute,
} as any)
const OperationsShipmentsRoute = OperationsShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => OperationsRoute,
} as any)
const OperationsReportsRoute = OperationsReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => OperationsRoute,
} as any)
const OperationsOrdersRoute = OperationsOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => OperationsRoute,
} as any)
const OperationsInventoryRoute = OperationsInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => OperationsRoute,
} as any)
const MerchantSubscriptionRoute = MerchantSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantSettlementsRoute = MerchantSettlementsRouteImport.update({
  id: '/settlements',
  path: '/settlements',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantSalesRoute = MerchantSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantRegisterRoute = MerchantRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantProfileRoute = MerchantProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantProductsRoute = MerchantProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantOrdersRoute = MerchantOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantInventoryRoute = MerchantInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantEmployeesRoute = MerchantEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantEmployeeReportsRoute = MerchantEmployeeReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => MerchantEmployeeRoute,
} as any)
const MerchantEmployeeProductsRoute =
  MerchantEmployeeProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => MerchantEmployeeRoute,
  } as any)
const MerchantEmployeeOrdersRoute = MerchantEmployeeOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => MerchantEmployeeRoute,
} as any)
const MerchantEmployeeInventoryRoute =
  MerchantEmployeeInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => MerchantEmployeeRoute,
  } as any)
const CustomerSupportRoute = CustomerSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerSearchRoute = CustomerSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerProfileRoute = CustomerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerNotificationsRoute = CustomerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerCheckoutRoute = CustomerCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerCategoriesRoute = CustomerCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerCartRoute = CustomerCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerAiSearchRoute = CustomerAiSearchRouteImport.update({
  id: '/ai-search',
  path: '/ai-search',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerAddressesRoute = CustomerAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => CustomerRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportTicketsRoute = AdminSupportTicketsRouteImport.update({
  id: '/support-tickets',
  path: '/support-tickets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMerchantsRoute = AdminMerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployeeUsersRoute = AdminEmployeeUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminEmployeeRoute,
} as any)
const AdminEmployeeSupportTicketsRoute =
  AdminEmployeeSupportTicketsRouteImport.update({
    id: '/support-tickets',
    path: '/support-tickets',
    getParentRoute: () => AdminEmployeeRoute,
  } as any)
const AdminEmployeeReportsRoute = AdminEmployeeReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminEmployeeRoute,
} as any)
const AdminEmployeeProductsRoute = AdminEmployeeProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminEmployeeRoute,
} as any)
const AdminEmployeeMerchantsRoute = AdminEmployeeMerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => AdminEmployeeRoute,
} as any)
const AdminEmployeeApplicationsRoute =
  AdminEmployeeApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AdminEmployeeRoute,
  } as any)
const CustomerOrdersIndexRoute = CustomerOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerProductIdRoute = CustomerProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerOrdersIdRoute = CustomerOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerCategoryIdRoute = CustomerCategoryIdRouteImport.update({
  id: '/category/$id',
  path: '/category/$id',
  getParentRoute: () => CustomerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-employee': typeof AdminEmployeeRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/login': typeof LoginRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/merchant-employee': typeof MerchantEmployeeRouteWithChildren
  '/operations': typeof OperationsRouteWithChildren
  '/role-redirect': typeof RoleRedirectRoute
  '/verify': typeof VerifyRoute
  '/admin-employee/applications': typeof AdminEmployeeApplicationsRoute
  '/admin-employee/merchants': typeof AdminEmployeeMerchantsRoute
  '/admin-employee/products': typeof AdminEmployeeProductsRoute
  '/admin-employee/reports': typeof AdminEmployeeReportsRoute
  '/admin-employee/support-tickets': typeof AdminEmployeeSupportTicketsRoute
  '/admin-employee/users': typeof AdminEmployeeUsersRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support-tickets': typeof AdminSupportTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/customer/addresses': typeof CustomerAddressesRoute
  '/customer/ai-search': typeof CustomerAiSearchRoute
  '/customer/cart': typeof CustomerCartRoute
  '/customer/categories': typeof CustomerCategoriesRoute
  '/customer/checkout': typeof CustomerCheckoutRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/search': typeof CustomerSearchRoute
  '/customer/support': typeof CustomerSupportRoute
  '/merchant-employee/inventory': typeof MerchantEmployeeInventoryRoute
  '/merchant-employee/orders': typeof MerchantEmployeeOrdersRoute
  '/merchant-employee/products': typeof MerchantEmployeeProductsRoute
  '/merchant-employee/reports': typeof MerchantEmployeeReportsRoute
  '/merchant/employees': typeof MerchantEmployeesRoute
  '/merchant/inventory': typeof MerchantInventoryRoute
  '/merchant/orders': typeof MerchantOrdersRoute
  '/merchant/products': typeof MerchantProductsRoute
  '/merchant/profile': typeof MerchantProfileRoute
  '/merchant/register': typeof MerchantRegisterRoute
  '/merchant/sales': typeof MerchantSalesRoute
  '/merchant/settlements': typeof MerchantSettlementsRoute
  '/merchant/subscription': typeof MerchantSubscriptionRoute
  '/operations/inventory': typeof OperationsInventoryRoute
  '/operations/orders': typeof OperationsOrdersRoute
  '/operations/reports': typeof OperationsReportsRoute
  '/operations/shipments': typeof OperationsShipmentsRoute
  '/admin-employee/': typeof AdminEmployeeIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/merchant-employee/': typeof MerchantEmployeeIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/operations/': typeof OperationsIndexRoute
  '/customer/category/$id': typeof CustomerCategoryIdRoute
  '/customer/orders/$id': typeof CustomerOrdersIdRoute
  '/customer/product/$id': typeof CustomerProductIdRoute
  '/customer/orders/': typeof CustomerOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/role-redirect': typeof RoleRedirectRoute
  '/verify': typeof VerifyRoute
  '/admin-employee/applications': typeof AdminEmployeeApplicationsRoute
  '/admin-employee/merchants': typeof AdminEmployeeMerchantsRoute
  '/admin-employee/products': typeof AdminEmployeeProductsRoute
  '/admin-employee/reports': typeof AdminEmployeeReportsRoute
  '/admin-employee/support-tickets': typeof AdminEmployeeSupportTicketsRoute
  '/admin-employee/users': typeof AdminEmployeeUsersRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support-tickets': typeof AdminSupportTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/customer/addresses': typeof CustomerAddressesRoute
  '/customer/ai-search': typeof CustomerAiSearchRoute
  '/customer/cart': typeof CustomerCartRoute
  '/customer/categories': typeof CustomerCategoriesRoute
  '/customer/checkout': typeof CustomerCheckoutRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/search': typeof CustomerSearchRoute
  '/customer/support': typeof CustomerSupportRoute
  '/merchant-employee/inventory': typeof MerchantEmployeeInventoryRoute
  '/merchant-employee/orders': typeof MerchantEmployeeOrdersRoute
  '/merchant-employee/products': typeof MerchantEmployeeProductsRoute
  '/merchant-employee/reports': typeof MerchantEmployeeReportsRoute
  '/merchant/employees': typeof MerchantEmployeesRoute
  '/merchant/inventory': typeof MerchantInventoryRoute
  '/merchant/orders': typeof MerchantOrdersRoute
  '/merchant/products': typeof MerchantProductsRoute
  '/merchant/profile': typeof MerchantProfileRoute
  '/merchant/register': typeof MerchantRegisterRoute
  '/merchant/sales': typeof MerchantSalesRoute
  '/merchant/settlements': typeof MerchantSettlementsRoute
  '/merchant/subscription': typeof MerchantSubscriptionRoute
  '/operations/inventory': typeof OperationsInventoryRoute
  '/operations/orders': typeof OperationsOrdersRoute
  '/operations/reports': typeof OperationsReportsRoute
  '/operations/shipments': typeof OperationsShipmentsRoute
  '/admin-employee': typeof AdminEmployeeIndexRoute
  '/admin': typeof AdminIndexRoute
  '/customer': typeof CustomerIndexRoute
  '/merchant-employee': typeof MerchantEmployeeIndexRoute
  '/merchant': typeof MerchantIndexRoute
  '/operations': typeof OperationsIndexRoute
  '/customer/category/$id': typeof CustomerCategoryIdRoute
  '/customer/orders/$id': typeof CustomerOrdersIdRoute
  '/customer/product/$id': typeof CustomerProductIdRoute
  '/customer/orders': typeof CustomerOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-employee': typeof AdminEmployeeRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/login': typeof LoginRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/merchant-employee': typeof MerchantEmployeeRouteWithChildren
  '/operations': typeof OperationsRouteWithChildren
  '/role-redirect': typeof RoleRedirectRoute
  '/verify': typeof VerifyRoute
  '/admin-employee/applications': typeof AdminEmployeeApplicationsRoute
  '/admin-employee/merchants': typeof AdminEmployeeMerchantsRoute
  '/admin-employee/products': typeof AdminEmployeeProductsRoute
  '/admin-employee/reports': typeof AdminEmployeeReportsRoute
  '/admin-employee/support-tickets': typeof AdminEmployeeSupportTicketsRoute
  '/admin-employee/users': typeof AdminEmployeeUsersRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support-tickets': typeof AdminSupportTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/customer/addresses': typeof CustomerAddressesRoute
  '/customer/ai-search': typeof CustomerAiSearchRoute
  '/customer/cart': typeof CustomerCartRoute
  '/customer/categories': typeof CustomerCategoriesRoute
  '/customer/checkout': typeof CustomerCheckoutRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/search': typeof CustomerSearchRoute
  '/customer/support': typeof CustomerSupportRoute
  '/merchant-employee/inventory': typeof MerchantEmployeeInventoryRoute
  '/merchant-employee/orders': typeof MerchantEmployeeOrdersRoute
  '/merchant-employee/products': typeof MerchantEmployeeProductsRoute
  '/merchant-employee/reports': typeof MerchantEmployeeReportsRoute
  '/merchant/employees': typeof MerchantEmployeesRoute
  '/merchant/inventory': typeof MerchantInventoryRoute
  '/merchant/orders': typeof MerchantOrdersRoute
  '/merchant/products': typeof MerchantProductsRoute
  '/merchant/profile': typeof MerchantProfileRoute
  '/merchant/register': typeof MerchantRegisterRoute
  '/merchant/sales': typeof MerchantSalesRoute
  '/merchant/settlements': typeof MerchantSettlementsRoute
  '/merchant/subscription': typeof MerchantSubscriptionRoute
  '/operations/inventory': typeof OperationsInventoryRoute
  '/operations/orders': typeof OperationsOrdersRoute
  '/operations/reports': typeof OperationsReportsRoute
  '/operations/shipments': typeof OperationsShipmentsRoute
  '/admin-employee/': typeof AdminEmployeeIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/merchant-employee/': typeof MerchantEmployeeIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/operations/': typeof OperationsIndexRoute
  '/customer/category/$id': typeof CustomerCategoryIdRoute
  '/customer/orders/$id': typeof CustomerOrdersIdRoute
  '/customer/product/$id': typeof CustomerProductIdRoute
  '/customer/orders/': typeof CustomerOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-employee'
    | '/customer'
    | '/login'
    | '/merchant'
    | '/merchant-employee'
    | '/operations'
    | '/role-redirect'
    | '/verify'
    | '/admin-employee/applications'
    | '/admin-employee/merchants'
    | '/admin-employee/products'
    | '/admin-employee/reports'
    | '/admin-employee/support-tickets'
    | '/admin-employee/users'
    | '/admin/applications'
    | '/admin/categories'
    | '/admin/employees'
    | '/admin/merchants'
    | '/admin/packages'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/support-tickets'
    | '/admin/users'
    | '/customer/addresses'
    | '/customer/ai-search'
    | '/customer/cart'
    | '/customer/categories'
    | '/customer/checkout'
    | '/customer/notifications'
    | '/customer/profile'
    | '/customer/search'
    | '/customer/support'
    | '/merchant-employee/inventory'
    | '/merchant-employee/orders'
    | '/merchant-employee/products'
    | '/merchant-employee/reports'
    | '/merchant/employees'
    | '/merchant/inventory'
    | '/merchant/orders'
    | '/merchant/products'
    | '/merchant/profile'
    | '/merchant/register'
    | '/merchant/sales'
    | '/merchant/settlements'
    | '/merchant/subscription'
    | '/operations/inventory'
    | '/operations/orders'
    | '/operations/reports'
    | '/operations/shipments'
    | '/admin-employee/'
    | '/admin/'
    | '/customer/'
    | '/merchant-employee/'
    | '/merchant/'
    | '/operations/'
    | '/customer/category/$id'
    | '/customer/orders/$id'
    | '/customer/product/$id'
    | '/customer/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/role-redirect'
    | '/verify'
    | '/admin-employee/applications'
    | '/admin-employee/merchants'
    | '/admin-employee/products'
    | '/admin-employee/reports'
    | '/admin-employee/support-tickets'
    | '/admin-employee/users'
    | '/admin/applications'
    | '/admin/categories'
    | '/admin/employees'
    | '/admin/merchants'
    | '/admin/packages'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/support-tickets'
    | '/admin/users'
    | '/customer/addresses'
    | '/customer/ai-search'
    | '/customer/cart'
    | '/customer/categories'
    | '/customer/checkout'
    | '/customer/notifications'
    | '/customer/profile'
    | '/customer/search'
    | '/customer/support'
    | '/merchant-employee/inventory'
    | '/merchant-employee/orders'
    | '/merchant-employee/products'
    | '/merchant-employee/reports'
    | '/merchant/employees'
    | '/merchant/inventory'
    | '/merchant/orders'
    | '/merchant/products'
    | '/merchant/profile'
    | '/merchant/register'
    | '/merchant/sales'
    | '/merchant/settlements'
    | '/merchant/subscription'
    | '/operations/inventory'
    | '/operations/orders'
    | '/operations/reports'
    | '/operations/shipments'
    | '/admin-employee'
    | '/admin'
    | '/customer'
    | '/merchant-employee'
    | '/merchant'
    | '/operations'
    | '/customer/category/$id'
    | '/customer/orders/$id'
    | '/customer/product/$id'
    | '/customer/orders'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-employee'
    | '/customer'
    | '/login'
    | '/merchant'
    | '/merchant-employee'
    | '/operations'
    | '/role-redirect'
    | '/verify'
    | '/admin-employee/applications'
    | '/admin-employee/merchants'
    | '/admin-employee/products'
    | '/admin-employee/reports'
    | '/admin-employee/support-tickets'
    | '/admin-employee/users'
    | '/admin/applications'
    | '/admin/categories'
    | '/admin/employees'
    | '/admin/merchants'
    | '/admin/packages'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/support-tickets'
    | '/admin/users'
    | '/customer/addresses'
    | '/customer/ai-search'
    | '/customer/cart'
    | '/customer/categories'
    | '/customer/checkout'
    | '/customer/notifications'
    | '/customer/profile'
    | '/customer/search'
    | '/customer/support'
    | '/merchant-employee/inventory'
    | '/merchant-employee/orders'
    | '/merchant-employee/products'
    | '/merchant-employee/reports'
    | '/merchant/employees'
    | '/merchant/inventory'
    | '/merchant/orders'
    | '/merchant/products'
    | '/merchant/profile'
    | '/merchant/register'
    | '/merchant/sales'
    | '/merchant/settlements'
    | '/merchant/subscription'
    | '/operations/inventory'
    | '/operations/orders'
    | '/operations/reports'
    | '/operations/shipments'
    | '/admin-employee/'
    | '/admin/'
    | '/customer/'
    | '/merchant-employee/'
    | '/merchant/'
    | '/operations/'
    | '/customer/category/$id'
    | '/customer/orders/$id'
    | '/customer/product/$id'
    | '/customer/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminEmployeeRoute: typeof AdminEmployeeRouteWithChildren
  CustomerRoute: typeof CustomerRouteWithChildren
  LoginRoute: typeof LoginRoute
  MerchantRoute: typeof MerchantRouteWithChildren
  MerchantEmployeeRoute: typeof MerchantEmployeeRouteWithChildren
  OperationsRoute: typeof OperationsRouteWithChildren
  RoleRedirectRoute: typeof RoleRedirectRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role-redirect': {
      id: '/role-redirect'
      path: '/role-redirect'
      fullPath: '/role-redirect'
      preLoaderRoute: typeof RoleRedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant-employee': {
      id: '/merchant-employee'
      path: '/merchant-employee'
      fullPath: '/merchant-employee'
      preLoaderRoute: typeof MerchantEmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-employee': {
      id: '/admin-employee'
      path: '/admin-employee'
      fullPath: '/admin-employee'
      preLoaderRoute: typeof AdminEmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/': {
      id: '/operations/'
      path: '/'
      fullPath: '/operations/'
      preLoaderRoute: typeof OperationsIndexRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/merchant/': {
      id: '/merchant/'
      path: '/'
      fullPath: '/merchant/'
      preLoaderRoute: typeof MerchantIndexRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant-employee/': {
      id: '/merchant-employee/'
      path: '/'
      fullPath: '/merchant-employee/'
      preLoaderRoute: typeof MerchantEmployeeIndexRouteImport
      parentRoute: typeof MerchantEmployeeRoute
    }
    '/customer/': {
      id: '/customer/'
      path: '/'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin-employee/': {
      id: '/admin-employee/'
      path: '/'
      fullPath: '/admin-employee/'
      preLoaderRoute: typeof AdminEmployeeIndexRouteImport
      parentRoute: typeof AdminEmployeeRoute
    }
    '/operations/shipments': {
      id: '/operations/shipments'
      path: '/shipments'
      fullPath: '/operations/shipments'
      preLoaderRoute: typeof OperationsShipmentsRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/operations/reports': {
      id: '/operations/reports'
      path: '/reports'
      fullPath: '/operations/reports'
      preLoaderRoute: typeof OperationsReportsRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/operations/orders': {
      id: '/operations/orders'
      path: '/orders'
      fullPath: '/operations/orders'
      preLoaderRoute: typeof OperationsOrdersRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/operations/inventory': {
      id: '/operations/inventory'
      path: '/inventory'
      fullPath: '/operations/inventory'
      preLoaderRoute: typeof OperationsInventoryRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/merchant/subscription': {
      id: '/merchant/subscription'
      path: '/subscription'
      fullPath: '/merchant/subscription'
      preLoaderRoute: typeof MerchantSubscriptionRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/settlements': {
      id: '/merchant/settlements'
      path: '/settlements'
      fullPath: '/merchant/settlements'
      preLoaderRoute: typeof MerchantSettlementsRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/sales': {
      id: '/merchant/sales'
      path: '/sales'
      fullPath: '/merchant/sales'
      preLoaderRoute: typeof MerchantSalesRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/register': {
      id: '/merchant/register'
      path: '/register'
      fullPath: '/merchant/register'
      preLoaderRoute: typeof MerchantRegisterRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/profile': {
      id: '/merchant/profile'
      path: '/profile'
      fullPath: '/merchant/profile'
      preLoaderRoute: typeof MerchantProfileRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/products': {
      id: '/merchant/products'
      path: '/products'
      fullPath: '/merchant/products'
      preLoaderRoute: typeof MerchantProductsRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/orders': {
      id: '/merchant/orders'
      path: '/orders'
      fullPath: '/merchant/orders'
      preLoaderRoute: typeof MerchantOrdersRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/inventory': {
      id: '/merchant/inventory'
      path: '/inventory'
      fullPath: '/merchant/inventory'
      preLoaderRoute: typeof MerchantInventoryRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/employees': {
      id: '/merchant/employees'
      path: '/employees'
      fullPath: '/merchant/employees'
      preLoaderRoute: typeof MerchantEmployeesRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant-employee/reports': {
      id: '/merchant-employee/reports'
      path: '/reports'
      fullPath: '/merchant-employee/reports'
      preLoaderRoute: typeof MerchantEmployeeReportsRouteImport
      parentRoute: typeof MerchantEmployeeRoute
    }
    '/merchant-employee/products': {
      id: '/merchant-employee/products'
      path: '/products'
      fullPath: '/merchant-employee/products'
      preLoaderRoute: typeof MerchantEmployeeProductsRouteImport
      parentRoute: typeof MerchantEmployeeRoute
    }
    '/merchant-employee/orders': {
      id: '/merchant-employee/orders'
      path: '/orders'
      fullPath: '/merchant-employee/orders'
      preLoaderRoute: typeof MerchantEmployeeOrdersRouteImport
      parentRoute: typeof MerchantEmployeeRoute
    }
    '/merchant-employee/inventory': {
      id: '/merchant-employee/inventory'
      path: '/inventory'
      fullPath: '/merchant-employee/inventory'
      preLoaderRoute: typeof MerchantEmployeeInventoryRouteImport
      parentRoute: typeof MerchantEmployeeRoute
    }
    '/customer/support': {
      id: '/customer/support'
      path: '/support'
      fullPath: '/customer/support'
      preLoaderRoute: typeof CustomerSupportRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/search': {
      id: '/customer/search'
      path: '/search'
      fullPath: '/customer/search'
      preLoaderRoute: typeof CustomerSearchRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/profile': {
      id: '/customer/profile'
      path: '/profile'
      fullPath: '/customer/profile'
      preLoaderRoute: typeof CustomerProfileRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/notifications': {
      id: '/customer/notifications'
      path: '/notifications'
      fullPath: '/customer/notifications'
      preLoaderRoute: typeof CustomerNotificationsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/checkout': {
      id: '/customer/checkout'
      path: '/checkout'
      fullPath: '/customer/checkout'
      preLoaderRoute: typeof CustomerCheckoutRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/categories': {
      id: '/customer/categories'
      path: '/categories'
      fullPath: '/customer/categories'
      preLoaderRoute: typeof CustomerCategoriesRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/cart': {
      id: '/customer/cart'
      path: '/cart'
      fullPath: '/customer/cart'
      preLoaderRoute: typeof CustomerCartRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/ai-search': {
      id: '/customer/ai-search'
      path: '/ai-search'
      fullPath: '/customer/ai-search'
      preLoaderRoute: typeof CustomerAiSearchRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/addresses': {
      id: '/customer/addresses'
      path: '/addresses'
      fullPath: '/customer/addresses'
      preLoaderRoute: typeof CustomerAddressesRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support-tickets': {
      id: '/admin/support-tickets'
      path: '/support-tickets'
      fullPath: '/admin/support-tickets'
      preLoaderRoute: typeof AdminSupportTicketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/merchants': {
      id: '/admin/merchants'
      path: '/merchants'
      fullPath: '/admin/merchants'
      preLoaderRoute: typeof AdminMerchantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin-employee/users': {
      id: '/admin-employee/users'
      path: '/users'
      fullPath: '/admin-employee/users'
      preLoaderRoute: typeof AdminEmployeeUsersRouteImport
      parentRoute: typeof AdminEmployeeRoute
    }
    '/admin-employee/support-tickets': {
      id: '/admin-employee/support-tickets'
      path: '/support-tickets'
      fullPath: '/admin-employee/support-tickets'
      preLoaderRoute: typeof AdminEmployeeSupportTicketsRouteImport
      parentRoute: typeof AdminEmployeeRoute
    }
    '/admin-employee/reports': {
      id: '/admin-employee/reports'
      path: '/reports'
      fullPath: '/admin-employee/reports'
      preLoaderRoute: typeof AdminEmployeeReportsRouteImport
      parentRoute: typeof AdminEmployeeRoute
    }
    '/admin-employee/products': {
      id: '/admin-employee/products'
      path: '/products'
      fullPath: '/admin-employee/products'
      preLoaderRoute: typeof AdminEmployeeProductsRouteImport
      parentRoute: typeof AdminEmployeeRoute
    }
    '/admin-employee/merchants': {
      id: '/admin-employee/merchants'
      path: '/merchants'
      fullPath: '/admin-employee/merchants'
      preLoaderRoute: typeof AdminEmployeeMerchantsRouteImport
      parentRoute: typeof AdminEmployeeRoute
    }
    '/admin-employee/applications': {
      id: '/admin-employee/applications'
      path: '/applications'
      fullPath: '/admin-employee/applications'
      preLoaderRoute: typeof AdminEmployeeApplicationsRouteImport
      parentRoute: typeof AdminEmployeeRoute
    }
    '/customer/orders/': {
      id: '/customer/orders/'
      path: '/orders'
      fullPath: '/customer/orders/'
      preLoaderRoute: typeof CustomerOrdersIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/product/$id': {
      id: '/customer/product/$id'
      path: '/product/$id'
      fullPath: '/customer/product/$id'
      preLoaderRoute: typeof CustomerProductIdRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/orders/$id': {
      id: '/customer/orders/$id'
      path: '/orders/$id'
      fullPath: '/customer/orders/$id'
      preLoaderRoute: typeof CustomerOrdersIdRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/category/$id': {
      id: '/customer/category/$id'
      path: '/category/$id'
      fullPath: '/customer/category/$id'
      preLoaderRoute: typeof CustomerCategoryIdRouteImport
      parentRoute: typeof CustomerRoute
    }
  }
}

interface AdminRouteChildren {
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  AdminMerchantsRoute: typeof AdminMerchantsRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportTicketsRoute: typeof AdminSupportTicketsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminMerchantsRoute: AdminMerchantsRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportTicketsRoute: AdminSupportTicketsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AdminEmployeeRouteChildren {
  AdminEmployeeApplicationsRoute: typeof AdminEmployeeApplicationsRoute
  AdminEmployeeMerchantsRoute: typeof AdminEmployeeMerchantsRoute
  AdminEmployeeProductsRoute: typeof AdminEmployeeProductsRoute
  AdminEmployeeReportsRoute: typeof AdminEmployeeReportsRoute
  AdminEmployeeSupportTicketsRoute: typeof AdminEmployeeSupportTicketsRoute
  AdminEmployeeUsersRoute: typeof AdminEmployeeUsersRoute
  AdminEmployeeIndexRoute: typeof AdminEmployeeIndexRoute
}

const AdminEmployeeRouteChildren: AdminEmployeeRouteChildren = {
  AdminEmployeeApplicationsRoute: AdminEmployeeApplicationsRoute,
  AdminEmployeeMerchantsRoute: AdminEmployeeMerchantsRoute,
  AdminEmployeeProductsRoute: AdminEmployeeProductsRoute,
  AdminEmployeeReportsRoute: AdminEmployeeReportsRoute,
  AdminEmployeeSupportTicketsRoute: AdminEmployeeSupportTicketsRoute,
  AdminEmployeeUsersRoute: AdminEmployeeUsersRoute,
  AdminEmployeeIndexRoute: AdminEmployeeIndexRoute,
}

const AdminEmployeeRouteWithChildren = AdminEmployeeRoute._addFileChildren(
  AdminEmployeeRouteChildren,
)

interface CustomerRouteChildren {
  CustomerAddressesRoute: typeof CustomerAddressesRoute
  CustomerAiSearchRoute: typeof CustomerAiSearchRoute
  CustomerCartRoute: typeof CustomerCartRoute
  CustomerCategoriesRoute: typeof CustomerCategoriesRoute
  CustomerCheckoutRoute: typeof CustomerCheckoutRoute
  CustomerNotificationsRoute: typeof CustomerNotificationsRoute
  CustomerProfileRoute: typeof CustomerProfileRoute
  CustomerSearchRoute: typeof CustomerSearchRoute
  CustomerSupportRoute: typeof CustomerSupportRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
  CustomerCategoryIdRoute: typeof CustomerCategoryIdRoute
  CustomerOrdersIdRoute: typeof CustomerOrdersIdRoute
  CustomerProductIdRoute: typeof CustomerProductIdRoute
  CustomerOrdersIndexRoute: typeof CustomerOrdersIndexRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerAddressesRoute: CustomerAddressesRoute,
  CustomerAiSearchRoute: CustomerAiSearchRoute,
  CustomerCartRoute: CustomerCartRoute,
  CustomerCategoriesRoute: CustomerCategoriesRoute,
  CustomerCheckoutRoute: CustomerCheckoutRoute,
  CustomerNotificationsRoute: CustomerNotificationsRoute,
  CustomerProfileRoute: CustomerProfileRoute,
  CustomerSearchRoute: CustomerSearchRoute,
  CustomerSupportRoute: CustomerSupportRoute,
  CustomerIndexRoute: CustomerIndexRoute,
  CustomerCategoryIdRoute: CustomerCategoryIdRoute,
  CustomerOrdersIdRoute: CustomerOrdersIdRoute,
  CustomerProductIdRoute: CustomerProductIdRoute,
  CustomerOrdersIndexRoute: CustomerOrdersIndexRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

interface MerchantRouteChildren {
  MerchantEmployeesRoute: typeof MerchantEmployeesRoute
  MerchantInventoryRoute: typeof MerchantInventoryRoute
  MerchantOrdersRoute: typeof MerchantOrdersRoute
  MerchantProductsRoute: typeof MerchantProductsRoute
  MerchantProfileRoute: typeof MerchantProfileRoute
  MerchantRegisterRoute: typeof MerchantRegisterRoute
  MerchantSalesRoute: typeof MerchantSalesRoute
  MerchantSettlementsRoute: typeof MerchantSettlementsRoute
  MerchantSubscriptionRoute: typeof MerchantSubscriptionRoute
  MerchantIndexRoute: typeof MerchantIndexRoute
}

const MerchantRouteChildren: MerchantRouteChildren = {
  MerchantEmployeesRoute: MerchantEmployeesRoute,
  MerchantInventoryRoute: MerchantInventoryRoute,
  MerchantOrdersRoute: MerchantOrdersRoute,
  MerchantProductsRoute: MerchantProductsRoute,
  MerchantProfileRoute: MerchantProfileRoute,
  MerchantRegisterRoute: MerchantRegisterRoute,
  MerchantSalesRoute: MerchantSalesRoute,
  MerchantSettlementsRoute: MerchantSettlementsRoute,
  MerchantSubscriptionRoute: MerchantSubscriptionRoute,
  MerchantIndexRoute: MerchantIndexRoute,
}

const MerchantRouteWithChildren = MerchantRoute._addFileChildren(
  MerchantRouteChildren,
)

interface MerchantEmployeeRouteChildren {
  MerchantEmployeeInventoryRoute: typeof MerchantEmployeeInventoryRoute
  MerchantEmployeeOrdersRoute: typeof MerchantEmployeeOrdersRoute
  MerchantEmployeeProductsRoute: typeof MerchantEmployeeProductsRoute
  MerchantEmployeeReportsRoute: typeof MerchantEmployeeReportsRoute
  MerchantEmployeeIndexRoute: typeof MerchantEmployeeIndexRoute
}

const MerchantEmployeeRouteChildren: MerchantEmployeeRouteChildren = {
  MerchantEmployeeInventoryRoute: MerchantEmployeeInventoryRoute,
  MerchantEmployeeOrdersRoute: MerchantEmployeeOrdersRoute,
  MerchantEmployeeProductsRoute: MerchantEmployeeProductsRoute,
  MerchantEmployeeReportsRoute: MerchantEmployeeReportsRoute,
  MerchantEmployeeIndexRoute: MerchantEmployeeIndexRoute,
}

const MerchantEmployeeRouteWithChildren =
  MerchantEmployeeRoute._addFileChildren(MerchantEmployeeRouteChildren)

interface OperationsRouteChildren {
  OperationsInventoryRoute: typeof OperationsInventoryRoute
  OperationsOrdersRoute: typeof OperationsOrdersRoute
  OperationsReportsRoute: typeof OperationsReportsRoute
  OperationsShipmentsRoute: typeof OperationsShipmentsRoute
  OperationsIndexRoute: typeof OperationsIndexRoute
}

const OperationsRouteChildren: OperationsRouteChildren = {
  OperationsInventoryRoute: OperationsInventoryRoute,
  OperationsOrdersRoute: OperationsOrdersRoute,
  OperationsReportsRoute: OperationsReportsRoute,
  OperationsShipmentsRoute: OperationsShipmentsRoute,
  OperationsIndexRoute: OperationsIndexRoute,
}

const OperationsRouteWithChildren = OperationsRoute._addFileChildren(
  OperationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminEmployeeRoute: AdminEmployeeRouteWithChildren,
  CustomerRoute: CustomerRouteWithChildren,
  LoginRoute: LoginRoute,
  MerchantRoute: MerchantRouteWithChildren,
  MerchantEmployeeRoute: MerchantEmployeeRouteWithChildren,
  OperationsRoute: OperationsRouteWithChildren,
  RoleRedirectRoute: RoleRedirectRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
