FROM oven/bun:1 AS builder

WORKDIR /app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

COPY . .

RUN bun run build

FROM oven/bun:1

WORKDIR /app

COPY --from=builder /app .

EXPOSE 3000

ENV NODE_ENV=production

CMD ["bun", ".output/server/index.mjs"]